# -*- coding: utf-8 -*-
"""
Generate the Divvy-2017 PDST-GCN dataset from the physics-consistent V7
10-minute closed-system reconstruction.

The script is intentionally downstream-only: it DOES NOT infer bike states,
operator relocations, or fleet membership again.  Those are taken from the
V6.4 -> V7 reconstruction.

Forecasting task
----------------
10-minute sampling; 6 historical states -> 6 future states (1 h -> 1 h).
The model node set is

    node 0             : mesoscopic in-transit node
    nodes 1, ..., N-1  : V7 active Divvy stations

Node feature channels are compatible with the current PDST-GCN code:
    0: bike inventory/state count
    1: time-of-day in [0,1)
    2: day-of-week in {1/7,...,1}

Dynamic graph
-------------
For every valid forecasting sample, one one-hour predefined dynamic graph is
formed from the SAME historical hour as the sample input.  It uses physically
observed V7 transitions:
    station -> 0       user departures
    0 -> station       user arrivals
    station -> station operator relocation
Weights are transition counts.  The graph is directed; the model constructs
forward/backward diffusion matrices from it.

The dynamic graphs are stored sparsely.  A dense tensor of shape roughly
(4454, 568, 568) would be several GB, so forcing the old dense adj_matrices
format is wasteful.  lib/utils.py in PDSTGCN-1 materializes only the current
mini-batch on the GPU/CPU.

Static graph
------------
Built from TRAINING-PERIOD support only (to avoid topology leakage from the
validation/test period).  It is undirected for the ASTGCN Chebyshev branch.
Observed training user-OD and relocation relations are included, and node 0 is
connected to stations that participate in mesoscopic transitions.

Typical local usage
-------------------
1. Run the supplied upstream Divvy V6.4/V7 reconstruction scripts.
2. Edit the USER SETTINGS below if your paths differ.
3. Run:
       python data_generate.py
4. Then:
       python prepareData.py --config configurations/DIVVY_astgcn.conf
       python train_ASTGCN_r.py --config configurations/DIVVY_astgcn.conf
"""

from __future__ import annotations

import json
import math
import pickle
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd


# =============================================================================
# USER SETTINGS
# =============================================================================

V7_ROOT = Path(
    r"D:/physic_predict_bike/divvy_2017_physics_closed_active_v7_10min_from_v64"
)
RAW_ROOT = Path(r"D:/physic_predict_bike/divvy_2017_physics_raw")

# Output is inside this project by default.
PROJECT_ROOT = Path(__file__).resolve().parent
OUT_ROOT = PROJECT_ROOT / "data" / "DIVVY"
CONFIG_PATH = PROJECT_ROOT / "configurations" / "DIVVY_astgcn.conf"

INPUT_STEPS = 6
PRED_STEPS = 6
POINTS_PER_HOUR = 6
TRAIN_RATIO = 0.60
VAL_RATIO = 0.20
TEST_RATIO = 0.20

# V7 files.
V7_ARRAYS = V7_ROOT / "closed_system_v7_10min_arrays.npz"
V7_USER_OD = V7_ROOT / "user_od_flows_10min_sparse_v7.csv.gz"
V7_RELOCATION_OD = V7_ROOT / "relocation_od_flows_10min_sparse_v7.csv.gz"
V7_ACTIVE_STATIONS = V7_ROOT / "active_stations_v7.csv"

# Historical coordinates generated by download_divvy_2017_physics_dataset.py.
STATION_METADATA = RAW_ROOT / "metadata" / "station_metadata_from_historical_window.csv"
INVENTORY_MAIN = RAW_ROOT / "station_inventory" / "divvy_station_inventory_main_window.csv"

# Output files.
SIGNAL_PATH = OUT_ROOT / "DIVVY.npz"
DYNAMIC_PATH = OUT_ROOT / "dynamic_graph_sparse.npz"
STATIC_EDGE_PATH = OUT_ROOT / "DIVVY.csv"
STATIC_ADJ_PATH = OUT_ROOT / "static_adjacency.npz"
STATIC_CONN_PKL = OUT_ROOT / "adj_DIVVY.pkl"
STATIC_DIST_PKL = OUT_ROOT / "adj_DIVVY_distance.pkl"
NODE_MAPPING_PATH = OUT_ROOT / "node_mapping.csv"
SAMPLE_INDEX_PATH = OUT_ROOT / "sample_index.csv"
META_PATH = OUT_ROOT / "dataset_meta.json"


# =============================================================================
# HELPERS
# =============================================================================

def banner(text: str) -> None:
    print("\n" + "=" * 100)
    print(text)
    print("=" * 100)


def require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")


def normalize_id_series(s: pd.Series) -> pd.Series:
    out = s.astype("string").str.strip()
    out = out.replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA, "None": pd.NA, "<NA>": pd.NA})
    out = out.str.replace(r"^(-?\d+)\.0$", r"\1", regex=True)
    return out


def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371000.0
    p1 = math.radians(lat1)
    p2 = math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2.0) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2.0) ** 2
    return 2.0 * r * math.atan2(math.sqrt(a), math.sqrt(max(1.0 - a, 0.0)))


def interval_index(ts: pd.Series, t0: pd.Timestamp, freq: pd.Timedelta) -> np.ndarray:
    x = pd.to_datetime(ts, errors="coerce")
    vals = ((x - t0) / freq).to_numpy(dtype=float)
    return np.floor(vals + 1e-9).astype(np.int64)


def load_coordinates(station_ids: List[str]) -> pd.DataFrame:
    """Return one row per station_id with station_name/lat/lon where available."""
    station_set = set(station_ids)
    pieces: List[pd.DataFrame] = []

    if STATION_METADATA.exists():
        m = pd.read_csv(STATION_METADATA, low_memory=False)
        id_col = "id" if "id" in m.columns else ("station_id" if "station_id" in m.columns else None)
        if id_col is not None:
            m[id_col] = normalize_id_series(m[id_col])
            keep = [id_col]
            for c in ["station_name", "latitude", "longitude"]:
                if c in m.columns:
                    keep.append(c)
            z = m[m[id_col].isin(station_set)][keep].copy()
            z = z.rename(columns={id_col: "station_id"})
            pieces.append(z)

    # Fallback to the inventory file for missing coordinates.
    if INVENTORY_MAIN.exists():
        inv = pd.read_csv(INVENTORY_MAIN, low_memory=False)
        id_col = "id" if "id" in inv.columns else ("station_id" if "station_id" in inv.columns else None)
        if id_col is not None and {"latitude", "longitude"}.issubset(inv.columns):
            inv[id_col] = normalize_id_series(inv[id_col])
            inv["latitude"] = pd.to_numeric(inv["latitude"], errors="coerce")
            inv["longitude"] = pd.to_numeric(inv["longitude"], errors="coerce")
            inv = inv[inv[id_col].isin(station_set) & inv["latitude"].notna() & inv["longitude"].notna()].copy()
            if "timestamp" in inv.columns:
                inv["timestamp"] = pd.to_datetime(inv["timestamp"], errors="coerce")
                inv = inv.sort_values("timestamp")
            keep = [id_col, "latitude", "longitude"]
            if "station_name" in inv.columns:
                keep.append("station_name")
            inv = inv.groupby(id_col, as_index=False, sort=False).tail(1)[keep]
            inv = inv.rename(columns={id_col: "station_id"})
            pieces.append(inv)

    # Active-station file is useful for names even when coordinate files are missing.
    if V7_ACTIVE_STATIONS.exists():
        a = pd.read_csv(V7_ACTIVE_STATIONS, low_memory=False)
        if "station_id" in a.columns:
            a["station_id"] = normalize_id_series(a["station_id"])
            keep = ["station_id"] + (["station_name"] if "station_name" in a.columns else [])
            pieces.append(a[a["station_id"].isin(station_set)][keep].copy())

    out = pd.DataFrame({"station_id": station_ids})
    out["station_name"] = ""
    out["latitude"] = np.nan
    out["longitude"] = np.nan

    for p in pieces:
        p = p.drop_duplicates("station_id", keep="last").set_index("station_id")
        for c in ["station_name", "latitude", "longitude"]:
            if c not in p.columns:
                continue
            mapping = p[c]
            vals = out["station_id"].map(mapping)
            if c == "station_name":
                mask = vals.notna() & (vals.astype(str).str.len() > 0)
                out.loc[mask, c] = vals[mask].astype(str)
            else:
                vals = pd.to_numeric(vals, errors="coerce")
                mask = vals.notna()
                out.loc[mask, c] = vals[mask]

    return out


def add_edge(counter: Dict[Tuple[int, int], int], u: int, v: int, w: int) -> None:
    if w <= 0 or u == v:
        return
    counter[(int(u), int(v))] = int(counter.get((int(u), int(v)), 0)) + int(w)


def update_counter(total: Dict[Tuple[int, int], int], delta: Dict[Tuple[int, int], int], sign: int) -> None:
    for e, w in delta.items():
        new_w = int(total.get(e, 0)) + sign * int(w)
        if new_w == 0:
            total.pop(e, None)
        elif new_w < 0:
            raise RuntimeError(f"Rolling graph count became negative for edge {e}: {new_w}")
        else:
            total[e] = new_w


def write_config(num_nodes: int, fleet_size: int) -> None:
    text = f"""[Data]
adj_filename = ./data/DIVVY/DIVVY.csv
graph_signal_matrix_filename = ./data/DIVVY/DIVVY.npz
dynamic_graph_filename = ./data/DIVVY/dynamic_graph_sparse.npz
num_of_vertices = {num_nodes}
points_per_hour = {POINTS_PER_HOUR}
num_for_predict = {PRED_STEPS}
len_input = {INPUT_STEPS}
dataset_name = DIVVY
fleet_size = {fleet_size}

[Training]
ctx = 0
in_channels = 3
nb_block = 2
K = 3
nb_chev_filter = 64
nb_time_filter = 64
batch_size = 8
model_name = pdstgcn
num_of_weeks = 0
num_of_days = 0
num_of_hours = 1
start_epoch = 0
epochs = 100
learning_rate = 0.001
loss_function = mse
metric_method = unmask
missing_value = 0.0
seed = 20260913
"""
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(text, encoding="utf-8")


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    banner("DIVVY V7 -> PDST-GCN 10-MIN DATA GENERATION")

    require_file(V7_ARRAYS)
    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    z = np.load(V7_ARRAYS, allow_pickle=True)
    required_keys = {
        "station_ids",
        "state_times_ns",
        "reconstructed_bike_inventory",
        "reconstructed_user_in_transit",
        "user_departures",
        "user_arrivals",
    }
    missing = required_keys - set(z.files)
    if missing:
        raise KeyError(f"V7 NPZ missing keys: {sorted(missing)}")

    station_ids = [str(x) for x in z["station_ids"].tolist()]
    state_times = pd.to_datetime(z["state_times_ns"].astype(np.int64))
    station_bikes = z["reconstructed_bike_inventory"].astype(np.int32)
    in_transit = z["reconstructed_user_in_transit"].astype(np.int32)
    departures = z["user_departures"].astype(np.int32)
    arrivals = z["user_arrivals"].astype(np.int32)

    if station_bikes.shape[0] != len(state_times):
        raise RuntimeError("state time count does not match reconstructed inventory")
    if station_bikes.shape[1] != len(station_ids):
        raise RuntimeError("station count does not match station_ids")
    if departures.shape != (len(state_times) - 1, len(station_ids)):
        raise RuntimeError("user_departures has unexpected shape")
    if arrivals.shape != departures.shape:
        raise RuntimeError("user_arrivals has unexpected shape")

    dt = pd.Series(state_times).diff().dropna()
    if len(dt) and not (dt == pd.Timedelta(minutes=10)).all():
        raise RuntimeError("V7 state grid is not uniformly 10 minutes")

    T = len(state_times)
    n_station = len(station_ids)
    n_nodes = n_station + 1
    sample_count = T - INPUT_STEPS - PRED_STEPS + 1
    if sample_count <= 0:
        raise RuntimeError("Not enough V7 states for the requested 6->6 task")

    total = station_bikes.sum(axis=1).astype(np.int64) + in_transit.astype(np.int64)
    if np.any(total != total[0]):
        raise RuntimeError(
            f"V7 physical mass is not constant: min={total.min()}, max={total.max()}"
        )
    fleet_size = int(total[0])

    print(f"State boundaries          : {T:,}")
    print(f"Transition intervals      : {T-1:,}")
    print(f"Real stations             : {n_station:,}")
    print(f"Model nodes (+ node 0)    : {n_nodes:,}")
    print(f"Fixed fleet size          : {fleet_size:,}")
    print(f"Task                      : {INPUT_STEPS} history -> {PRED_STEPS} future")
    print(f"Valid samples             : {sample_count:,}")
    print(f"Alignment loss            : {INPUT_STEPS + PRED_STEPS - 1} (= 11, not old 23)")

    # -------------------------------------------------------------------------
    # 1. Node mapping and graph signal tensor.
    # -------------------------------------------------------------------------
    banner("BUILD NODE MAPPING + GRAPH SIGNAL")
    coord = load_coordinates(station_ids)

    mapping = pd.DataFrame(
        {
            "node_index": np.arange(n_nodes, dtype=np.int32),
            "node_id": ["0"] + station_ids,
            "node_type": ["mesoscopic_in_transit"] + ["real_station"] * n_station,
            "station_name": ["__IN_TRANSIT__"] + coord["station_name"].astype(str).tolist(),
            "latitude": [np.nan] + coord["latitude"].tolist(),
            "longitude": [np.nan] + coord["longitude"].tolist(),
        }
    )
    mapping.to_csv(NODE_MAPPING_PATH, index=False, encoding="utf-8-sig")

    data = np.zeros((T, n_nodes, 3), dtype=np.float32)
    data[:, 0, 0] = in_transit.astype(np.float32)
    data[:, 1:, 0] = station_bikes.astype(np.float32)

    minutes = state_times.hour * 60 + state_times.minute
    tod = np.asarray(minutes, dtype=np.float32) / 1440.0
    dow = (np.asarray(state_times.weekday, dtype=np.float32) + 1.0) / 7.0
    data[:, :, 1] = tod[:, None]
    data[:, :, 2] = dow[:, None]

    np.savez_compressed(
        SIGNAL_PATH,
        data=data,
        state_times_ns=state_times.to_numpy(dtype="datetime64[ns]").astype(np.int64),
        node_ids=np.asarray(["0"] + station_ids, dtype=str),
        fleet_size=np.asarray([fleet_size], dtype=np.int64),
    )
    print(f"Signal tensor             : {data.shape} -> {SIGNAL_PATH}")

    # -------------------------------------------------------------------------
    # 2. Interval-level physical transition edges.
    # -------------------------------------------------------------------------
    banner("BUILD PHYSICAL INTERVAL EDGES")
    interval_edges: List[Dict[Tuple[int, int], int]] = [defaultdict(int) for _ in range(T - 1)]

    # Node 0 is index 0; station j in V7 becomes model node j+1.
    for k in range(T - 1):
        dep_idx = np.flatnonzero(departures[k])
        arr_idx = np.flatnonzero(arrivals[k])
        d = interval_edges[k]
        for j in dep_idx:
            add_edge(d, int(j) + 1, 0, int(departures[k, j]))
        for j in arr_idx:
            add_edge(d, 0, int(j) + 1, int(arrivals[k, j]))

    station_to_node = {sid: i + 1 for i, sid in enumerate(station_ids)}
    reloc_rows_used = 0
    if V7_RELOCATION_OD.exists():
        r = pd.read_csv(V7_RELOCATION_OD, low_memory=False)
        if len(r):
            for c in ["origin_station_id", "destination_station_id"]:
                if c not in r.columns:
                    raise ValueError(f"Relocation OD file missing {c}")
                r[c] = normalize_id_series(r[c])
            r["count"] = pd.to_numeric(r["count"], errors="coerce").fillna(0).astype(int)
            k_idx = interval_index(
                r["interval_start"], pd.Timestamp(state_times[0]), pd.Timedelta(minutes=10)
            )
            for kk, row in zip(k_idx, r.itertuples(index=False)):
                if kk < 0 or kk >= T - 1:
                    continue
                u = station_to_node.get(str(row.origin_station_id))
                v = station_to_node.get(str(row.destination_station_id))
                if u is None or v is None:
                    continue
                add_edge(interval_edges[int(kk)], u, v, int(row.count))
                reloc_rows_used += 1

    print(f"Relocation OD rows used   : {reloc_rows_used:,}")
    print(f"Interval edge events sum  : {sum(sum(d.values()) for d in interval_edges):,}")

    # -------------------------------------------------------------------------
    # 3. Sample-aligned one-hour dynamic graphs, sparse packed representation.
    # -------------------------------------------------------------------------
    banner("BUILD SAMPLE-ALIGNED DYNAMIC GRAPHS")
    split1 = int(sample_count * TRAIN_RATIO)
    split2 = int(sample_count * (TRAIN_RATIO + VAL_RATIO))

    graph_ptr = [0]
    src_all: List[int] = []
    dst_all: List[int] = []
    weight_all: List[float] = []

    rolling: Dict[Tuple[int, int], int] = {}
    for k in range(INPUT_STEPS):
        update_counter(rolling, interval_edges[k], +1)

    static_training_support: set[Tuple[int, int]] = set()

    for g in range(sample_count):
        for (u, v), w in sorted(rolling.items()):
            if w <= 0:
                continue
            src_all.append(u)
            dst_all.append(v)
            weight_all.append(float(w))
            if g < split1:
                static_training_support.add((u, v))
        graph_ptr.append(len(src_all))

        # Slide the one-hour graph to the next sample.
        if g + 1 < sample_count:
            update_counter(rolling, interval_edges[g], -1)
            update_counter(rolling, interval_edges[g + INPUT_STEPS], +1)

    np.savez_compressed(
        DYNAMIC_PATH,
        graph_ptr=np.asarray(graph_ptr, dtype=np.int64),
        src=np.asarray(src_all, dtype=np.int32),
        dst=np.asarray(dst_all, dtype=np.int32),
        weight=np.asarray(weight_all, dtype=np.float32),
        num_nodes=np.asarray([n_nodes], dtype=np.int32),
        num_graphs=np.asarray([sample_count], dtype=np.int32),
        input_steps=np.asarray([INPUT_STEPS], dtype=np.int32),
        pred_steps=np.asarray([PRED_STEPS], dtype=np.int32),
        alignment_trim=np.asarray([INPUT_STEPS + PRED_STEPS - 1], dtype=np.int32),
    )
    print(f"Dynamic graphs            : {sample_count:,}")
    print(f"Packed nonzero edges      : {len(src_all):,}")
    print(f"Dynamic graph file        : {DYNAMIC_PATH}")

    # -------------------------------------------------------------------------
    # 4. Static graph from TRAINING support only.
    #    Add observed training user-OD station-station relations as in the old
    #    static graph semantics, while keeping the graph undirected.
    # -------------------------------------------------------------------------
    banner("BUILD TRAINING-ONLY STATIC GRAPH")
    undirected_pairs: set[Tuple[int, int]] = set()

    def add_static_pair(u: int, v: int) -> None:
        if u == v:
            return
        a, b = (u, v) if u < v else (v, u)
        undirected_pairs.add((a, b))

    for u, v in static_training_support:
        add_static_pair(u, v)

    # Training cutoff includes the historical graph window of the last train sample.
    train_last_interval_exclusive = min(split1 - 1 + INPUT_STEPS, T - 1) if split1 else 0

    if V7_USER_OD.exists() and split1 > 0:
        uod = pd.read_csv(V7_USER_OD, low_memory=False)
        if len(uod):
            for c in ["origin_station_id", "destination_station_id"]:
                uod[c] = normalize_id_series(uod[c])
            kk = interval_index(
                uod["interval_start"], pd.Timestamp(state_times[0]), pd.Timedelta(minutes=10)
            )
            for k0, row in zip(kk, uod.itertuples(index=False)):
                if k0 < 0 or k0 >= train_last_interval_exclusive:
                    continue
                u = station_to_node.get(str(row.origin_station_id))
                v = station_to_node.get(str(row.destination_station_id))
                if u is not None and v is not None:
                    add_static_pair(u, v)

    # Coordinate maps for distance cost.  node 0 is conceptual: distance=0 on
    # every 0-related edge, matching the old project convention.
    lat = {i + 1: coord.iloc[i]["latitude"] for i in range(n_station)}
    lon = {i + 1: coord.iloc[i]["longitude"] for i in range(n_station)}

    edge_rows = []
    A = np.zeros((n_nodes, n_nodes), dtype=np.float32)
    D = np.zeros((n_nodes, n_nodes), dtype=np.float32)
    missing_coord_edges = 0

    for u, v in sorted(undirected_pairs):
        if u == 0 or v == 0:
            cost = 0.0
        else:
            vals = [lat.get(u), lon.get(u), lat.get(v), lon.get(v)]
            if all(pd.notna(x) for x in vals):
                cost = haversine_m(float(vals[0]), float(vals[1]), float(vals[2]), float(vals[3]))
            else:
                # Connectivity drives the current static ASTGCN branch; distance
                # is audit metadata.  Do not invent coordinates.
                cost = 0.0
                missing_coord_edges += 1

        # Write BOTH directions so the existing CSV loader is unambiguous.
        edge_rows.append((u, v, cost))
        edge_rows.append((v, u, cost))
        A[u, v] = A[v, u] = 1.0
        D[u, v] = D[v, u] = float(cost)

    pd.DataFrame(edge_rows, columns=["from", "to", "cost"]).to_csv(
        STATIC_EDGE_PATH, index=False
    )
    np.savez_compressed(STATIC_ADJ_PATH, adjacency=A, distance=D)
    with STATIC_CONN_PKL.open("wb") as f:
        pickle.dump(A, f)
    with STATIC_DIST_PKL.open("wb") as f:
        pickle.dump(D, f)

    print(f"Undirected static edges   : {len(undirected_pairs):,}")
    print(f"Edges missing coordinates : {missing_coord_edges:,}")
    print(f"Static CSV                : {STATIC_EDGE_PATH}")

    # -------------------------------------------------------------------------
    # 5. Exact sample index / chronological 60:20:20 split.
    # -------------------------------------------------------------------------
    banner("WRITE SAMPLE INDEX + CONFIG")
    rows = []
    for g in range(sample_count):
        label_idx = g + INPUT_STEPS
        target_last = label_idx + PRED_STEPS - 1
        split = "train" if g < split1 else ("val" if g < split2 else "test")
        rows.append(
            {
                "graph_id": g,
                "input_start_index": g,
                "input_end_index_inclusive": label_idx - 1,
                "target_start_index": label_idx,
                "target_end_index_inclusive": target_last,
                "input_start_time": state_times[g],
                "input_end_time": state_times[label_idx - 1],
                "target_start_time": state_times[label_idx],
                "target_end_time": state_times[target_last],
                "split": split,
            }
        )
    sample_df = pd.DataFrame(rows)
    sample_df.to_csv(SAMPLE_INDEX_PATH, index=False)

    write_config(n_nodes, fleet_size)

    meta = {
        "source_version": "V7_10min_from_V6_4",
        "signal_shape": list(data.shape),
        "real_station_count": n_station,
        "model_node_count": n_nodes,
        "mesoscopic_node_index": 0,
        "fleet_size": fleet_size,
        "state_boundary_count": T,
        "interval_count": T - 1,
        "sampling_minutes": 10,
        "points_per_hour": POINTS_PER_HOUR,
        "input_steps": INPUT_STEPS,
        "prediction_steps": PRED_STEPS,
        "alignment_trim": INPUT_STEPS + PRED_STEPS - 1,
        "sample_count": sample_count,
        "split_counts": {
            "train": split1,
            "val": split2 - split1,
            "test": sample_count - split2,
        },
        "dynamic_graph_semantics": {
            "window": "same historical hour as model input",
            "station_to_0": "V7 user departures",
            "0_to_station": "V7 user arrivals",
            "station_to_station": "V7 inferred operator relocation OD",
            "storage": "packed sparse per-sample directed weighted graph",
        },
        "static_graph_semantics": "training-period support only, undirected; physical support plus training user OD",
        "paths": {
            "signal": str(SIGNAL_PATH),
            "dynamic": str(DYNAMIC_PATH),
            "static_edges": str(STATIC_EDGE_PATH),
            "node_mapping": str(NODE_MAPPING_PATH),
            "sample_index": str(SAMPLE_INDEX_PATH),
            "config": str(CONFIG_PATH),
        },
    }
    META_PATH.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")

    print(sample_df["split"].value_counts(sort=False).to_string())
    print(f"Config                    : {CONFIG_PATH}")
    print(f"Metadata                  : {META_PATH}")

    banner("DATA GENERATION COMPLETE")
    print("Next commands:")
    print("  python prepareData.py --config configurations/DIVVY_astgcn.conf")
    print("  python train_ASTGCN_r.py --config configurations/DIVVY_astgcn.conf")


if __name__ == "__main__":
    main()
